package com.tallyinventory.portal;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.util.concurrent.*;

public class MainActivity extends Activity {
 final String BASE="https://tally-api-prod-production.up.railway.app"; // production API ExecutorService ex=Executors.newSingleThreadExecutor(); android.content.SharedPreferences sp; LinearLayout root; EditText user,pass; TextView status; String token="";
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("cache",0);showLogin();}
 TextView tv(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(16);t.setPadding(24,18,24,18);return t;}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,24,24,24);setContentView(root);}
 void showLogin(){base();root.addView(tv("TALLY INVENTORY PORTAL"));root.addView(tv("Connected to Railway API"));user=new EditText(this);user.setHint("Username");pass=new EditText(this);pass.setHint("Password");pass.setInputType(129);root.addView(user);root.addView(pass);Button x=new Button(this);x.setText("LOGIN");root.addView(x);status=tv("");root.addView(status);x.setOnClickListener(v->login());}
 void login(){status.setText("Signing in…");String u=user.getText().toString(),p=pass.getText().toString();ex.submit(()->{try{JSONObject j=post("/auth/login",new JSONObject().put("username",u).put("password",p),null);token=j.getString("access_token");sp.edit().putString("token",token).apply();runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->status.setText("Login failed: "+e.getMessage()));}});}
 void showHome(){base();root.addView(tv("TALLY INVENTORY PORTAL"));Button s=new Button(this);s.setText("STOCK / INVENTORY");Button l=new Button(this);l.setText("LEDGERS");Button r=new Button(this);r.setText("REFRESH DATA");root.addView(s);root.addView(l);root.addView(r);status=tv("Ready");root.addView(status);s.setOnClickListener(v->load("/api/stock","stock"));l.setOnClickListener(v->load("/api/ledgers","ledgers"));r.setOnClickListener(v->{load("/api/stock","stock");load("/api/ledgers","ledgers");});}
 void load(String path,String key){status.setText("Loading…");ex.submit(()->{try{JSONObject j=get(path);sp.edit().putString(key,j.toString()).apply();runOnUiThread(()->showData(key,j));}catch(Exception e){try{JSONObject j=new JSONObject(sp.getString(key,"{\"status\":\"NO CACHE\",\"items\":[]}"));runOnUiThread(()->showData(key,j));}catch(Exception z){runOnUiThread(()->status.setText("No connection and no cached data"));}}});}
 void showData(String key,JSONObject j){base();root.addView(tv(key.toUpperCase()));TextView out=tv(formatItems(j));root.addView(out);Button back=new Button(this);back.setText("BACK");root.addView(back);back.setOnClickListener(v->showHome());}
 String formatItems(JSONObject j){StringBuilder b=new StringBuilder();try{JSONArray a=j.optJSONArray("items");if(a==null||a.length()==0)return "No data available.\n\nIf the server is offline, the app will show the last cached data.";for(int i=0;i<a.length();i++){Object o=a.get(i);b.append(o.toString()).append("\n\n");}}catch(Exception e){b.append(j.toString());}return b.toString();}
 JSONObject get(String path)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod("GET");c.setRequestProperty("Authorization","Bearer "+token);return read(c);}
 JSONObject post(String path,JSONObject body,String secret)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes("UTF-8"));}return read(c);}
 JSONObject read(HttpURLConnection c)throws Exception{int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(in));StringBuilder b=new StringBuilder();String q;while((q=br.readLine())!=null)b.append(q);if(code>=400)throw new Exception(b.toString());return new JSONObject(b.toString());}
}